### ISSUE TITLE
Livebox scripts generate a lot of zombie processes

### ISSUE THREAD

**Issue by pythondz** [papo-o/domoticz_scripts#1]
*Current behavior :*

The livebox Dzvents script generates a lot of zombie processes every minutes :

`root     25023 24976  1 08:20 ?        00:00:01 /opt/domoticz/domoticz -dbase /config/domoticz.db -log /config/domoticz.log -www 8080
root     26370 25023  0 08:20 ?        00:00:00 [curl] <defunct>
root     26372 25023  0 08:20 ?        00:00:00 [rm] <defunct>
root     27581 25023  0 08:21 ?        00:00:00 [curl] <defunct>
root     27583 25023  0 08:21 ?        00:00:00 [rm] <defunct>`

This behavior threaten host stability.

**Comment by papo-o** [comment]
we removed some '&' at the end of the curl command in the latest version (1.13). it may solve the problem because we do not have a processe zombie anymore. 
does this solve the problem on your system?
