### ISSUE TITLE
alerteMeteoFrancePluie.lua author/auteur = papoo update/mise à jour = 28/04/2019 création = 09/03/2019

### ISSUE THREAD

**Issue by yoks33** [papo-o/domoticz_scripts#11]
Hello papoo, merci tout d'abord pour ce script, j'ai une petite question après avoir mis le script sur domoticz j'ai cette erreur "did not return a commandArray" pourriez vous m'aider svp merci

**Comment by yleroux** [comment]
Bonjour

Est-ce un script LUA ou bien dzEvent que vous avez créé ? Il me semble que les array sont dans LUA. Alors que là il s'agit d'un dzEvent bien que l'extension soit LUA.

**Comment by yoks33** [comment]
Merci beaucoup pour la réactivités en dzEvent effectivement plus d'erreurs :)

**Comment by yoks33** [comment]
j'ai rajouté une scene pour 6 électrovannes arrosage de 30 minutes qui ce déclenche une après l'autre.
![image](https://user-images.githubusercontent.com/68285851/87439427-1185e800-c5f1-11ea-8541-119e099cf857.png)
j'ai ajouter un blocky pour la météo qui va récupérer la partie info du jour de votre script et si "pas de précipitations" ou inférieur a 5mm/h et température supérieur  a 15° ça déclenche mon arrosage . si ça peut aider tant mieux :)
![image](https://user-images.githubusercontent.com/68285851/87439305-e69b9400-c5f0-11ea-842a-3406c64edc66.png)

**Comment by papo-o** [comment]
Merci BreizhCat pour le support et yoks33 pour l'exemple de blocky
