### ISSUE TITLE
erreur dans script

### ISSUE THREAD

**Issue by fanosd** [papo-o/domoticz_scripts#4]
Bonsoir,

J'ai copié et mis en place ce script, mais je ne comprends pas d'ou vient le pb :

Voici les logs : 

2019-11-13 21:20:00.386 Error: EventSystem: in /home/pi/domoticz/scripts/lua/script_time_givreauto_new.lua: /home/pi/domoticz/scripts/lua/script_time_givreauto_new.lua:158: <eof> expected near 'end'

**Comment by papo-o** [comment]
Bonjour,
tu utilises quel éditeur de texte pour tes scripts? 
Vérifies que l'encodage est bien utf8 sans bom. si ton éditeur ne te permet pas de modifier l'encodage, je te conseil notepad++ qui lui le permet.
ensuite penses à commenter la ligne 59 
ta clé API doit être inscrite dans une variable utilisateur de domoticz 
idem pour la latitude et longitude. 
si tu souhaites inscrire directement ces données dans ton script fait le lignes 36/37/38 et commentes (en ajoutant -- devant) les lignes 96/98/100 (ces lignes contiennent uservariables)
enfin j'ai effacé le fichier txt que tu a mis en ligne, il contenait ton API en clair

**Comment by fanosd** [comment]
Bonsoir,

Merci Papo-o.

J'utilisais 'vi' comme éditeur. J'ai testé 'nano' et je me suis aperçu qu'il manquait un']' en fin de commentaire ( --] au lieu de --]]   ). J'ai corrigé et n'ai plus mon message d'erreur dans les logs.

Maintenant il ne me reste plus qu'à comprendre comment avoir mon alerte sur le dashboard de Domoticz.

Merci encore.
