### ISSUE TITLE
Impossible de récupérer la liste des appels (erreur 504, timeout)

### ISSUE THREAD

**Issue by N0ury** [papo-o/domoticz_scripts#5]
Salut,

Je n'arrive pas à récupérer la liste des appels.
Voici la commande exécutée (exemple):
`curl -s -b myCookies -X POST -H 'Content-Type: application/x-sah-ws-4-call+json' -H 'X-Context: ijMdtoHreuLNPuCBR0zaygCnCZxMK1vf5ORMETH0heHVPSrsUmWqsexSHXugEjwv' -d '{{"service":"VoiceService.VoiceApplication","method":"getCallList","parameters":{}}}' http://192.168.1.1/ws`
et voici la réponse:
`<html><head><title>Gateway Timeout</title></head><body><h1>504 - Gateway Timeout</h1></body></html>`

D'autres commandes que celle-là fonctionnent. Ex récupération du statut du wifi en 2,4GH et en 5GHz.
Aurais-tu une idée du problème ?
J'utilise une Livebox 4

**Comment by N0ury** [comment]
Désolé, j'ai accidentellement ajouté des accolades.
Sujet résolu. Je ferme l'incident.

**Comment by papo-o** [comment]
Heureux que t'on problème soit résolu
