### ISSUE TITLE
Incorrect values with darksky.lua ?

### ISSUE THREAD

**Issue by biwizit** [papo-o/domoticz_scripts#6]
Hello,

When using darksky.lua, I do not have any error in the log and all the "wind" and "percentage" sensors are updated. But it seems to me that the script is not taking the correct values. For instance, in the log, the values printed are from j=29 to j=48, which is obviously not aligned with my requests (I only defined values/devices for info between 1h to 24h). Can you confirm that everything is OK on your side ?

Thank you in advance.

Regards.

**Comment by papo-o** [comment]
Hello,
everything works fine for me, I did not see any discrepancy between the values ​​displayed in the logs and their feedback in domoticz
Best regards.
