### ISSUE TITLE
Erreur d'exécution script synology

### ISSUE THREAD

**Issue by yatoub** [papo-o/domoticz_scripts#9]
Bonjour,

J'ai tenté d'installer le script pour gérer une NAS Synology par SNMP mais dans Domoticz je n'ai aucune info qui remonte (les senseurs ont les bon noms, l'ip et le password sont ok aussi)
Dans les logs Domoticz j'ai l'erreur suivante :
```log
2020-05-13 19:08:00.262 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2020-05-13 19:08:00.262 Error: dzVents: Error: (3.0.2) Synology Monitor v1.41 : An error occurred when calling event handler Synology
2020-05-13 19:08:00.262 Error: dzVents: Error: (3.0.2) Synology Monitor v1.41 : .../domoticz/scripts/dzVents/generated_scripts/Synology.lua:180: attempt to perform arithmetic on a string value (field '?')
```
J'ai regardé à la ligne 180 mais ne comprends pas pourquoi il y a une chaine a cet emplacement.

J'ai également tenté de modifier les OID pour le disques mais sans succès  

Pour aider au debug mon NAS est en DSM 6.2.2

**Comment by papo-o** [comment]
Bonjour, 
que contient votre ligne 180? la mienne est une ligne de log 
           dz.log('HDTotalGo : '..HDTotalGo,dz.LOG_DEBUG)
avez vous essayé de commenter cette ligne afin de ne plus avoir l'erreur et voir dans les logs le résultat brut de l'extraction des données?
en partant du principe que c'est le chiffre retourné par l'oid du HD total qui renvoie une erreur, avez vous essayé en ligne via la ligne de commande comme indiqué en préambule?
snmpwalk -v 2c -c PASSWORD NASIPADDRESS 1.3.6.1.2.1.25.2.3.1.5.51 (ou .38 ou .41) cela dépend plus de la version matériel que de la version DSM apparemment

**Comment by yatoub** [comment]
J'avais une ligne de décalage par rapport à vous, ma 180 est 
`HDTotalGo = dz.utils.round((results[2] *  results[1] / 1024 / 1024 / 1024/1024),2)`

La piste de la version matérielle était bonne, j'avais positionné le mauvais oid en confondant avec la version DSM.

Avec l'oid en .38 le problème ne se présente plus, merci de votre aide.

**Comment by papo-o** [comment]
Heureux que votre problème soit résolu.
